apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-plus-ingress-conf
data:
  # Adding new entries here will make them appear as files in the deployment.
  # Please update k8s.io/k8s.io/README.md when you update this file
  dash.conf: |

        # NGINX Plus APIs
        server {
            listen 8088;

            root /usr/share/nginx/html;

            access_log off;

            location  = /dashboard.html {
            }

            location /api {
                api write=off;
            }
        }
